[[Randompack]]
arch = "aarch64"
git-tree-sha1 = "263ae15a02750072c639e9cce0ebe0467af6201f"
os = "macos"

    [[Randompack.download]]
    sha256 = "9917015d9d0f2224700141660491b114908d2d520f1e57b19dd4002d42f3a04a"
    url = "https://github.com/JuliaBinaryWrappers/Randompack_jll.jl/releases/download/Randompack-v0.1.6+0/Randompack.v0.1.6.aarch64-apple-darwin.tar.gz"
[[Randompack]]
arch = "aarch64"
git-tree-sha1 = "958d1c875b31271a5f97c2a5e70d06ff2ab103ec"
libc = "glibc"
os = "linux"

    [[Randompack.download]]
    sha256 = "e9a162e8df3e791a441f2d03234c67ca8b35a7d52800e90c8d6c1b780903b9e7"
    url = "https://github.com/JuliaBinaryWrappers/Randompack_jll.jl/releases/download/Randompack-v0.1.6+0/Randompack.v0.1.6.aarch64-linux-gnu.tar.gz"
[[Randompack]]
arch = "aarch64"
git-tree-sha1 = "082edf517c8a9a5e77ab29f3b5c543edbf1e8a34"
libc = "musl"
os = "linux"

    [[Randompack.download]]
    sha256 = "0767e604da2146c446fa03b81157cda3e2972efe814ba5626b9e16e5973dabdf"
    url = "https://github.com/JuliaBinaryWrappers/Randompack_jll.jl/releases/download/Randompack-v0.1.6+0/Randompack.v0.1.6.aarch64-linux-musl.tar.gz"
[[Randompack]]
arch = "aarch64"
git-tree-sha1 = "ea55a33b6202478c7ac442205ca93076fc41c489"
os = "freebsd"

    [[Randompack.download]]
    sha256 = "1e1a089abc86f2386037ef7b2d26d51572784b497c4b3b3a438c133bc165b663"
    url = "https://github.com/JuliaBinaryWrappers/Randompack_jll.jl/releases/download/Randompack-v0.1.6+0/Randompack.v0.1.6.aarch64-unknown-freebsd.tar.gz"
[[Randompack]]
arch = "powerpc64le"
git-tree-sha1 = "7492cb70544de17d840b0be27d9988132fd7c690"
libc = "glibc"
os = "linux"

    [[Randompack.download]]
    sha256 = "91bb907db09380e6083182dd0e57a260f78b0c55b019fc99ce36870abfc1acfa"
    url = "https://github.com/JuliaBinaryWrappers/Randompack_jll.jl/releases/download/Randompack-v0.1.6+0/Randompack.v0.1.6.powerpc64le-linux-gnu.tar.gz"
[[Randompack]]
arch = "riscv64"
git-tree-sha1 = "f11fd2fd81bac28296a46ed6936ebb7b5047fb0c"
libc = "glibc"
os = "linux"

    [[Randompack.download]]
    sha256 = "6830c8e68084c3d2de232a23ba370bbfcf35c1ee5c21174a7b3bab428f3ec5d7"
    url = "https://github.com/JuliaBinaryWrappers/Randompack_jll.jl/releases/download/Randompack-v0.1.6+0/Randompack.v0.1.6.riscv64-linux-gnu.tar.gz"
[[Randompack]]
arch = "x86_64"
git-tree-sha1 = "1c3167096c0f6f281b3e7bd838bff616833e3751"
os = "macos"

    [[Randompack.download]]
    sha256 = "c6b5e6050493b1593369ac6481a00b7046f3848e1b42f35face359b9e30e4535"
    url = "https://github.com/JuliaBinaryWrappers/Randompack_jll.jl/releases/download/Randompack-v0.1.6+0/Randompack.v0.1.6.x86_64-apple-darwin.tar.gz"
[[Randompack]]
arch = "x86_64"
git-tree-sha1 = "4e0f59dc1b9fc2ff7542b40521f23bf49ec40a32"
libc = "glibc"
os = "linux"

    [[Randompack.download]]
    sha256 = "f7b79d09738dd8feff899e5ba5c676ddfc2c4f8cbbcbd19f27cb3fe2ae3d552d"
    url = "https://github.com/JuliaBinaryWrappers/Randompack_jll.jl/releases/download/Randompack-v0.1.6+0/Randompack.v0.1.6.x86_64-linux-gnu.tar.gz"
[[Randompack]]
arch = "x86_64"
git-tree-sha1 = "ef8f4976a63bd82da1180815d31a2be8a184fcf4"
libc = "musl"
os = "linux"

    [[Randompack.download]]
    sha256 = "229a120d15e93c8ac20828985fe4290ba51eab6b670c9614768ad9515adc9a27"
    url = "https://github.com/JuliaBinaryWrappers/Randompack_jll.jl/releases/download/Randompack-v0.1.6+0/Randompack.v0.1.6.x86_64-linux-musl.tar.gz"
[[Randompack]]
arch = "x86_64"
git-tree-sha1 = "74d8961a001f8bc04ddae41275ea634cc9120695"
os = "freebsd"

    [[Randompack.download]]
    sha256 = "7254239ca1684fdd5c832dce9be44c0ef0ed5bead9f5b333a5c43fd31569c64a"
    url = "https://github.com/JuliaBinaryWrappers/Randompack_jll.jl/releases/download/Randompack-v0.1.6+0/Randompack.v0.1.6.x86_64-unknown-freebsd.tar.gz"
[[Randompack]]
arch = "x86_64"
git-tree-sha1 = "36d3774515d3dc00e9f8a836d565b88629b6be86"
os = "windows"

    [[Randompack.download]]
    sha256 = "1f83972db01b0139f69139ae80bd348ae546aff77ea6548b398f4773d1f6a5fb"
    url = "https://github.com/JuliaBinaryWrappers/Randompack_jll.jl/releases/download/Randompack-v0.1.6+0/Randompack.v0.1.6.x86_64-w64-mingw32.tar.gz"
