# Autogenerated wrapper script for Randompack_jll for x86_64-linux-musl
export librandompack

using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("Randompack")
JLLWrappers.@declare_library_product(librandompack, "librandompack.so")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        librandompack,
        "lib/librandompack.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
